import { Octokit } from "@octokit/rest";

const GITHUB_OWNER = "morepudding";

// ============================================================
// Eden Studio app repo — for Eve's feature workshop
// ============================================================

const EDEN_REPO = "aigamestudio";

/**
 * List all text files in the Eden Studio app repo (non-recursive wrapper
 * using the Git trees API for efficiency).
 */
export async function listEdenRepoFiles(): Promise<string[]> {
  const octokit = getOctokit();

  const SKIP = /^(node_modules|\.next|\.git|dist|out|public)\//;
  const INCLUDE = /\.(ts|tsx|js|jsx|json|md|css|html|txt|ya?ml)$/i;

  try {
    const { data: refData } = await octokit.git.getRef({
      owner: GITHUB_OWNER,
      repo: EDEN_REPO,
      ref: "heads/main",
    });

    const { data: commitData } = await octokit.git.getCommit({
      owner: GITHUB_OWNER,
      repo: EDEN_REPO,
      commit_sha: refData.object.sha,
    });

    const { data: treeData } = await octokit.git.getTree({
      owner: GITHUB_OWNER,
      repo: EDEN_REPO,
      tree_sha: commitData.tree.sha,
      recursive: "true",
    });

    return (treeData.tree ?? [])
      .filter((item) => item.type === "blob" && !!item.path)
      .map((item) => item.path as string)
      .filter((p) => !SKIP.test(p) && INCLUDE.test(p));
  } catch {
    return [];
  }
}

/**
 * Read a file from the Eden Studio app repo.
 * Returns null if not found.
 */
export async function readEdenFile(path: string): Promise<string | null> {
  return getFileContent(EDEN_REPO, path);
}

/**
 * Build a focused codebase summary for Eve.
 * Returns file tree + content of up to 6 key files (prioritised by relevance).
 */
export async function buildEdenCodebaseContext(
  relevantPaths?: string[]
): Promise<string> {
  const allFiles = await listEdenRepoFiles();
  const fileTree = allFiles.map((p) => `  ${p}`).join("\n");

  const pathsToRead = relevantPaths?.length
    ? relevantPaths.slice(0, 6)
    : allFiles
        .filter(
          (p) =>
            p.startsWith("app/") ||
            p.startsWith("lib/") ||
            p === "CLAUDE.md"
        )
        .slice(0, 6);

  const fileContents = await Promise.all(
    pathsToRead.map(async (p) => {
      const content = await readEdenFile(p);
      if (!content) return null;
      const preview = content.split("\n").slice(0, 80).join("\n");
      return `\n### ${p}\n\`\`\`\n${preview}${content.split("\n").length > 80 ? "\n// ...truncated" : ""}\n\`\`\``;
    })
  );

  const snippets = fileContents.filter(Boolean).join("\n");

  return `## Repo Eden Studio (morepudding/aigamestudio)\n\n### Fichiers disponibles\n${fileTree}\n${snippets}`;
}

export interface RepoTextFileSnapshot {
  path: string;
  content: string;
}

const SNAPSHOT_FILE_REGEX = /\.(ts|tsx|js|jsx|json|md|css|html|txt|ya?ml)$/i;
const SNAPSHOT_SKIP_REGEX = /(^|\/)(node_modules|dist|build|coverage|\.git|public)(\/|$)/;

function getOctokit(): Octokit {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error("GITHUB_TOKEN is not defined");
  }
  return new Octokit({ auth: token });
}

// ============================================================
// Repo management
// ============================================================

/**
 * Create a new private GitHub repository under the owner account.
 * Idempotent: if the repo already exists, returns its info instead of throwing.
 */
export async function createRepo(
  name: string,
  description: string
): Promise<{ url: string; fullName: string }> {
  const octokit = getOctokit();

  try {
    const { data } = await octokit.repos.createForAuthenticatedUser({
      name,
      description,
      private: true,
      auto_init: true,
    });
    return { url: data.html_url, fullName: data.full_name };
  } catch (err: unknown) {
    // 422 = repo already exists — return existing repo info
    if (
      err &&
      typeof err === "object" &&
      "status" in err &&
      (err as { status: number }).status === 422
    ) {
      const { data } = await octokit.repos.get({ owner: GITHUB_OWNER, repo: name });
      return { url: data.html_url, fullName: data.full_name };
    }
    throw err;
  }
}

/**
 * Push an initial directory structure to a freshly created repo.
 * Uses a multi-file commit via the Git Trees API (single commit, no repeated calls).
 */
export async function initRepoStructure(
  repoName: string,
  projectTitle: string
): Promise<void> {
  const octokit = getOctokit();

  // Files to create in the initial commit
  const initialFiles: { path: string; content: string }[] = [
    {
      path: "README.md",
      content: `# ${projectTitle}\n\nGenerated by Eden Studio.\n`,
    },
    {
      path: "docs/gdd.md",
      content: `# Game Design Document — ${projectTitle}\n\n> À remplir par le Game Designer.\n`,
    },
    {
      path: "docs/tech-spec.md",
      content: `# Spécification Technique — ${projectTitle}\n\n> À remplir par le Lead Dev.\n`,
    },
    {
      path: "docs/data-arch.md",
      content: `# Architecture Data & État — ${projectTitle}\n\n> À remplir.\n`,
    },
    {
      path: "docs/asset-list.md",
      content: `# Asset List — ${projectTitle}\n\n> À remplir par le Lead Artist.\n`,
    },
    {
      path: "docs/backlog.md",
      content: `# Backlog de Développement — ${projectTitle}\n\n> À générer par le Producer.\n`,
    },
    { path: "src/.gitkeep", content: "" },
    { path: "assets/.gitkeep", content: "" },
  ];

  // Get the current HEAD of main (created by auto_init)
  const { data: refData } = await octokit.git.getRef({
    owner: GITHUB_OWNER,
    repo: repoName,
    ref: "heads/main",
  });
  const baseCommitSha = refData.object.sha;

  const { data: baseCommit } = await octokit.git.getCommit({
    owner: GITHUB_OWNER,
    repo: repoName,
    commit_sha: baseCommitSha,
  });
  const baseTreeSha = baseCommit.tree.sha;

  // Create blobs sequentially to avoid git-lock conflicts
  const blobs: { data: { sha: string } }[] = [];
  for (const file of initialFiles) {
    const blob = await octokit.git.createBlob({
      owner: GITHUB_OWNER,
      repo: repoName,
      content: Buffer.from(file.content).toString("base64"),
      encoding: "base64",
    });
    blobs.push(blob);
  }

  // Create tree on top of existing base tree
  const { data: treeData } = await octokit.git.createTree({
    owner: GITHUB_OWNER,
    repo: repoName,
    base_tree: baseTreeSha,
    tree: initialFiles.map((file, idx) => ({
      path: file.path,
      mode: "100644" as const,
      type: "blob" as const,
      sha: blobs[idx].data.sha,
    })),
  });

  // Create commit with parent
  const { data: commitData } = await octokit.git.createCommit({
    owner: GITHUB_OWNER,
    repo: repoName,
    message: "chore: init Eden Studio project structure",
    tree: treeData.sha,
    parents: [baseCommitSha],
  });

  // Update main branch to point to new commit
  await octokit.git.updateRef({
    owner: GITHUB_OWNER,
    repo: repoName,
    ref: "heads/main",
    sha: commitData.sha,
  });
}

/**
 * Ensure the base concept docs exist in the repository.
 * This repairs repos that were created before the full bootstrap completed.
 */
export async function ensureProjectDocs(
  repoName: string,
  projectTitle: string
): Promise<void> {
  const expectedDocs: { path: string; content: string }[] = [
    {
      path: "docs/gdd.md",
      content: `# Game Design Document — ${projectTitle}\n\n> À remplir par le Game Designer.\n`,
    },
    {
      path: "docs/tech-spec.md",
      content: `# Spécification Technique — ${projectTitle}\n\n> À remplir par le Lead Dev.\n`,
    },
    {
      path: "docs/data-arch.md",
      content: `# Architecture Data & État — ${projectTitle}\n\n> À remplir.\n`,
    },
    {
      path: "docs/asset-list.md",
      content: `# Asset List — ${projectTitle}\n\n> À remplir par le Lead Artist.\n`,
    },
    {
      path: "docs/backlog.md",
      content: `# Backlog de Développement — ${projectTitle}\n\n> À générer par le Producer.\n`,
    },
  ];

  const existingDocs = new Set(await listFiles(repoName, "docs"));

  for (const doc of expectedDocs) {
    if (existingDocs.has(doc.path)) continue;
    await pushFile(
      repoName,
      doc.path,
      doc.content,
      `[eden] bootstrap: add missing ${doc.path.split("/").pop()}`
    );
  }
}

// ============================================================
// File operations
// ============================================================

/**
 * Push (create or update) a file in the repository.
 */
export async function pushFile(
  repoName: string,
  path: string,
  content: string,
  commitMessage: string
): Promise<void> {
  const octokit = getOctokit();

  // GitHub rejects paths starting with "./" or ending with a slash
  path = path.replace(/^\.\//, "").replace(/\/+$/, "");
  if (!path) throw new Error("pushFile: path cannot be empty");

  // Check if file already exists to get its SHA (required for updates)
  let existingSha: string | undefined;
  try {
    const { data } = await octokit.repos.getContent({
      owner: GITHUB_OWNER,
      repo: repoName,
      path,
    });
    if (!Array.isArray(data) && data.type === "file") {
      existingSha = data.sha;
    }
  } catch {
    // File does not exist — will be created
  }

  await octokit.repos.createOrUpdateFileContents({
    owner: GITHUB_OWNER,
    repo: repoName,
    path,
    message: commitMessage,
    content: Buffer.from(content).toString("base64"),
    sha: existingSha,
  });
}

/**
 * Read the decoded content of a file from the repository.
 * Returns null if the file does not exist.
 */
export async function getFileContent(
  repoName: string,
  path: string
): Promise<string | null> {
  const octokit = getOctokit();

  try {
    const { data } = await octokit.repos.getContent({
      owner: GITHUB_OWNER,
      repo: repoName,
      path,
    });

    if (Array.isArray(data) || data.type !== "file") {
      return null;
    }

    if ("content" in data && data.content) {
      return Buffer.from(data.content, "base64").toString("utf-8");
    }

    return null;
  } catch {
    return null;
  }
}

/**
 * List file paths inside a directory (non-recursive).
 * Returns an empty array if the path does not exist.
 */
export async function listFiles(
  repoName: string,
  path: string = ""
): Promise<string[]> {
  const octokit = getOctokit();

  try {
    const { data } = await octokit.repos.getContent({
      owner: GITHUB_OWNER,
      repo: repoName,
      path,
    });

    if (!Array.isArray(data)) {
      return [];
    }

    return data.map((item) => item.path);
  } catch {
    return [];
  }
}

// ============================================================
// GitHub Pages
// ============================================================

/**
 * Active GitHub Pages sur la branche main du repo.
 * Idempotent : si Pages est déjà actif, retourne l'URL existante.
 * Retourne l'URL publique du mini-jeu.
 */
export async function enableGithubPages(repoName: string): Promise<string> {
  const octokit = getOctokit();

  // Vérifier si Pages est déjà actif
  try {
    const { data } = await octokit.repos.getPages({
      owner: GITHUB_OWNER,
      repo: repoName,
    });
    return data.html_url ?? "";
  } catch {
    // Pages non actif — on l'active
  }

  await octokit.repos.createPagesSite({
    owner: GITHUB_OWNER,
    repo: repoName,
    source: { branch: "main", path: "/" },
  });

  // L'URL est prévisible même avant que le build soit prêt
  return `https://${GITHUB_OWNER}.github.io/${repoName}/`;
}

/**
 * Attend que GitHub Pages ait terminé son déploiement.
 * Poll toutes les 5s jusqu'à ce que l'URL réponde avec un 2xx ou timeout (3 min).
 * Retourne l'URL finale.
 */
export async function waitForPagesDeployment(
  pagesUrl: string,
  timeoutMs = 180_000
): Promise<{ ready: boolean; url: string }> {
  const deadline = Date.now() + timeoutMs;
  const interval = 5_000;

  while (Date.now() < deadline) {
    try {
      const res = await fetch(pagesUrl, { method: "HEAD" });
      if (res.ok) return { ready: true, url: pagesUrl };
    } catch {
      // Pas encore prêt
    }
    await new Promise((resolve) => setTimeout(resolve, interval));
  }

  return { ready: false, url: pagesUrl };
}

function scoreSnapshotPath(path: string): number {
  if (path === "README.md") return 100;
  if (path === "docs/data-arch.md") return 95;
  if (path === "docs/asset-list.md") return 90;
  if (path.startsWith("src/assets/")) return 80;
  if (path.startsWith("src/core/")) return 75;
  if (path.startsWith("src/state/")) return 70;
  if (path.startsWith("src/systems/")) return 65;
  if (path.startsWith("src/components/")) return 60;
  if (path.startsWith("docs/")) return 30;
  return 10;
}

/**
 * Read a focused recursive snapshot of the repository text files.
 * Prioritises source files and supporting docs that are most useful for LLM analysis.
 */
export async function getRepositorySnapshot(
  repoName: string,
  options?: { maxFiles?: number; maxFileChars?: number }
): Promise<RepoTextFileSnapshot[]> {
  const octokit = getOctokit();
  const maxFiles = options?.maxFiles ?? 12;
  const maxFileChars = options?.maxFileChars ?? 5000;

  const { data: repo } = await octokit.repos.get({
    owner: GITHUB_OWNER,
    repo: repoName,
  });

  const { data: refData } = await octokit.git.getRef({
    owner: GITHUB_OWNER,
    repo: repoName,
    ref: `heads/${repo.default_branch}`,
  });

  const { data: commitData } = await octokit.git.getCommit({
    owner: GITHUB_OWNER,
    repo: repoName,
    commit_sha: refData.object.sha,
  });

  const { data: treeData } = await octokit.git.getTree({
    owner: GITHUB_OWNER,
    repo: repoName,
    tree_sha: commitData.tree.sha,
    recursive: "true",
  });

  const candidatePaths = (treeData.tree ?? [])
    .filter((item) => item.type === "blob" && !!item.path)
    .map((item) => item.path as string)
    .filter((path) => SNAPSHOT_FILE_REGEX.test(path))
    .filter((path) => !SNAPSHOT_SKIP_REGEX.test(path))
    .sort((left, right) => {
      const scoreDiff = scoreSnapshotPath(right) - scoreSnapshotPath(left);
      return scoreDiff !== 0 ? scoreDiff : left.localeCompare(right);
    })
    .slice(0, maxFiles);

  const files = await Promise.all(
    candidatePaths.map(async (path) => {
      const content = await getFileContent(repoName, path);
      if (!content) return null;
      return {
        path,
        content: content.length > maxFileChars ? `${content.slice(0, maxFileChars)}\n\n[...truncated]` : content,
      } satisfies RepoTextFileSnapshot;
    })
  );

  return files.filter((file): file is RepoTextFileSnapshot => file !== null);
}
