-- Migration 019: Brainstorming system
-- Replaces the decision wizard with a conversational multi-agent brainstorming
-- flow that scopes the game concept before GDD generation.

-- ============================================================
-- 1. Brainstorming sessions
-- ============================================================
CREATE TABLE IF NOT EXISTS brainstorming_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,

  -- Agents selected for this brainstorming (slugs)
  agent_slugs TEXT[] NOT NULL DEFAULT '{}',

  -- Phase tracking
  -- Phases: 'game-design' | 'programming' | 'art' | 'dynamic' | 'synthesis' | 'completed'
  current_phase TEXT NOT NULL DEFAULT 'game-design',
  phases_completed TEXT[] NOT NULL DEFAULT '{}',

  -- Synthesized scope (populated after synthesis phase)
  scope_summary TEXT,

  -- GDD generation state
  gdd_v1 TEXT,
  gdd_critique_questions JSONB, -- array of { id, question, options: string[] | null }
  gdd_answers JSONB,            -- { [questionId]: string }
  gdd_v2 TEXT,
  gdd_finalized BOOLEAN NOT NULL DEFAULT false,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_brainstorming_project ON brainstorming_sessions(project_id);

-- ============================================================
-- 2. Brainstorming messages
-- ============================================================
CREATE TABLE IF NOT EXISTS brainstorming_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES brainstorming_sessions(id) ON DELETE CASCADE,

  -- 'user' | 'agent' | 'system'
  role TEXT NOT NULL CHECK (role IN ('user', 'agent', 'system')),

  -- agent slug (null for user/system messages)
  agent_slug TEXT REFERENCES agents(slug),

  -- Phase this message belongs to
  phase TEXT NOT NULL,

  content TEXT NOT NULL,

  -- Is this a dynamic follow-up question generated by AI?
  is_dynamic BOOLEAN NOT NULL DEFAULT false,

  -- Is this a template question from the fixed list?
  question_key TEXT,

  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_brainstorming_messages_session ON brainstorming_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_brainstorming_messages_phase ON brainstorming_messages(session_id, phase);

-- ============================================================
-- 3. Auto-update updated_at on sessions
-- ============================================================
CREATE OR REPLACE FUNCTION update_brainstorming_sessions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS brainstorming_sessions_updated_at ON brainstorming_sessions;
CREATE TRIGGER brainstorming_sessions_updated_at
  BEFORE UPDATE ON brainstorming_sessions
  FOR EACH ROW EXECUTE FUNCTION update_brainstorming_sessions_updated_at();

-- ============================================================
-- 4. Add brainstorming_session_id to projects for quick lookup
-- ============================================================
ALTER TABLE projects ADD COLUMN IF NOT EXISTS brainstorming_session_id UUID REFERENCES brainstorming_sessions(id);

-- ============================================================
-- 5. Drop decisions_ready dependency from pipeline (we no longer
--    gate on it — GDD finalization replaces this check)
-- ============================================================
-- We keep the decisions_ready column for backwards compat but
-- producerService will use gdd_finalized instead.
