-- Migration 029: Cache personality bio generated by AI per agent
-- Prevents re-generating the same prose on every collaborator page load.

ALTER TABLE agents
  ADD COLUMN IF NOT EXISTS personality_bio TEXT DEFAULT NULL;
